name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  run_tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Required when using an activated conda environment in steps
        # See https://github.com/conda-incubator/setup-miniconda#IMPORTANT
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade setuptools
        run: |
          pip3 install wheel --upgrade
          pip3 install setuptools --upgrade

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: deepmap
          environment-file: environment.yml

      - name: Conda Info
        run: |
          conda info
          conda list

      - name: Convert notebooks to scripts
        run: |
          jupyter nbconvert --to script *.ipynb --output-dir .
        working-directory: ./notebooks

      - name: Run all scripts
        run: |
          for f in *.py; do python "$f"; done
        working-directory: ./notebooks